mensajeria:
  drivername: postgresql
  dbname: bd-OLTP
  user: postgres
  password: "sayjn123"
  host: localhost
  port: "5432"

ETL_PRO:
  drivername: postgresql
  dbname: etl_process
  user: postgres
  password: "sayjn123"
  host: localhost
  port: "5432"